# Generated by Django 5.0.7 on 2024-07-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(null=True, upload_to='Premiums')),
                ('Image2', models.ImageField(blank=True, null=True, upload_to='Premiums')),
                ('Image3', models.ImageField(blank=True, null=True, upload_to='Premiums')),
                ('Image4', models.ImageField(blank=True, null=True, upload_to='Premiums')),
                ('Image5', models.ImageField(blank=True, null=True, upload_to='Premiums')),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
