# Generated by Django 5.0.7 on 2024-07-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorShade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DoorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HangingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Color_shade',
            field=models.ManyToManyField(blank=True, to='Core.colorshade'),
        ),
        migrations.AddField(
            model_name='product',
            name='Door_type',
            field=models.ManyToManyField(blank=True, to='Core.doortype'),
        ),
        migrations.AddField(
            model_name='product',
            name='Hanging_position',
            field=models.ManyToManyField(blank=True, to='Core.hangingposition'),
        ),
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.ManyToManyField(blank=True, to='Core.size'),
        ),
    ]
