# Generated by Django 5.0.7 on 2024-07-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_remove_product_door_type_delete_doortype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Color_shade',
            field=models.ManyToManyField(blank=True, null=True, to='Core.colorshade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.ManyToManyField(blank=True, null=True, to='Core.size'),
        ),
    ]
