# Generated by Django 5.0.7 on 2024-07-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_product_color_shade_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Size',
            new_name='Sizes',
        ),
    ]
