# Generated by Django 5.0.7 on 2024-07-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_rename_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
