# Generated by Django 5.0.7 on 2024-07-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_quoterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=15)),
                ('Hanging_position', models.CharField(blank=True, max_length=50, null=True)),
                ('Color_shade', models.CharField(blank=True, max_length=50, null=True)),
                ('Size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
