# Generated by Django 5.0.7 on 2024-07-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindDealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
            ],
        ),
    ]
