# Generated by Django 5.0.7 on 2024-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_finddealers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=15)),
                ('Business', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
            ],
        ),
    ]
