# Generated by Django 5.0.7 on 2024-07-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_newdealers'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdealers',
            name='Email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
