# Generated by Django 5.0.7 on 2024-07-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_newdealers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=15)),
                ('WarrantyCode', models.CharField(max_length=15)),
                ('Dealer', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
    ]
