# Generated by Django 5.0.7 on 2024-07-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='Is_read',
            field=models.BooleanField(default=False),
        ),
    ]
