# Generated by Django 5.0.7 on 2024-07-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_quote_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='finddealers',
            name='Is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newdealers',
            name='Is_read',
            field=models.BooleanField(default=False),
        ),
    ]
