# Generated by Django 5.0.7 on 2024-07-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_finddealers_is_read_newdealers_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Link', models.CharField(max_length=250)),
            ],
        ),
    ]
