# Generated by Django 5.0.7 on 2024-07-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_alter_blogs_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Email', models.EmailField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=20, null=True)),
                ('Message', models.TextField()),
            ],
        ),
    ]
