# Generated by Django 5.0.7 on 2024-08-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_quote_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Door_type_1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='Door_type_2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
