# Generated by Django 5.0.7 on 2024-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_product_door_type_1_product_door_type_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Door_type_3',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
