# Generated by Django 5.0.7 on 2024-08-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_product_door_type_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Door_type',
        ),
    ]
