# Generated by Django 5.0.7 on 2024-08-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_remove_product_door_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Premiums'),
        ),
    ]
