# Generated by Django 5.0.7 on 2024-08-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Door_type_3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
