# Generated by Django 5.0.7 on 2024-08-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0027_alter_product_door_type_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Door_type_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Door_type_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
